title: TRUTHWEB 
author: J. Freeman
email: truth.gh@protonmail.com
description: > # this means to ignore newlines until "twitter_username:"
  TRUTHWEB hosts the objective and subjective musings of J. Freeman, a veteran journalist with experience documenting current events throughout the world. After being fired for his accurate coverage of current events in London, J. Freeman moved to Prague and began his career in freelancing journalism.

# social link
github_username: truthweb
rss: rss
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com


show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - archive

# Build settings
theme: minima
markdown: kramdown

plugins:
 - jekyll-feed
 - jekyll-seo-tag
